name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: test_pylint
        uses: Silleellie/pylint-github-action@v1
        with:
          package-path: src
          python-version: 3.11

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}

          message: |
            *Pylint Report*:
            $(cat pylint_report.txt)
            https://img.shields.io/badge/pylint-1.95-red?logo=python&logoColor=white