name: WPS
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.18.0
            
